spring.application.name=cloudsight-poc-hybrid
server.port=${PORT:9092}

cloudsight.api.base-url=${CLOUDSIGHT_API_BASE_URL:https://dargio-cloudsight-backend.onrender.com}
cloudsight.workspace.email=${CLOUDSIGHT_WORKSPACE_EMAIL:test@dargio.com}
cloudsight.workspace.password=${CLOUDSIGHT_WORKSPACE_PASSWORD:password123}
